<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
</head>
<body>
<div class="panel admin-panel margin-top" id="add">
  <div class="panel-head"><input type="button" value="添加小说" id="add_button"></div>
  <div class="body-content" style="display: none;"  id="edit_window">
    <form method="post" class="form-x" action="/article/replace" id="edit_window_form">
      <div class="form-group" >
          <div class="field">
              <label class="label" style="width: 80px;">名称：</label>
              <input type="text" class="input w50" id="class_name" name="class_name" placeholder="">
          </div>
          <div class="field">
              <label class="label" style="width: 80px;">上级菜单</label>
              <select id="parent_class" name="parent_class" class="input w50">
                  <option value="0"></option>
                  <?php foreach($this->first_class as $key=>$value){?>
                      <option value="<?=$key?>"><?=$value?></option>
                  <?php }?>
              </select>
          </div>
          <div class="field">
              <label class="label" style="width: 80px;" >简介</label>
              <textarea  rows="5" class="input w50" name="description" id="description"></textarea>
          </div>
      </div>

          <input type="hidden" value="" name="class_id" id="class_id">
          <button class="button bg-main icon-check-square-o" type="submit"> 提交</button>
          <button class="button bg-main icon-check-square-o" type="button" onclick="$('#edit_window').hide()"> 取消</button>
      </div>

    </form>
  </div>
</div>
<div class="panel admin-panel">
    <div class="panel-head"><strong class="icon-reorder"> 小说列表管理</strong></div>
    <div style="padding-left: 50px;text-align: center;">
        <form action="/novel/list" method="get">
            <span>作者：</span>
            <select name="author_id">
                <?php foreach ($this->author_list as $value){ ?>
                    <option value="<?=$value['id']."_".$value['author_name']?>"><?=$value['author_name']?></option>
                <?php }?>
            </select>
            <input type="submit" value="搜索">
        </form>
    </div>
    <hr>
    <table class="table table-hover text-center">
        <thead>
        <tr>
            <th class="table-check"><input type="checkbox" class="tpl-table-fz-check"></th>
            <th class="table-id">ID</th>
            <th class="table-title">分类名称</th>
            <th class="table-type">上级分类</th>
            <th class="table-date am-hide-sm-only">修改日期</th>
            <th class="table-set">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->class_list as $value){?>
            <tr>

                <td><input type="checkbox"></td>

                <td><?=$value['id']?></td>
                <td><?=$value['name']?></td>
                <td><?=$value['parent_id']?></td>

                <td class="am-hide-sm-only"><?=date("Y-m-d H:i:s",$value['update_time'])?></td>
                <td>
                    <div class="am-btn-toolbar">
                        <div class="am-btn-group am-btn-group-xs">
                            <button class="am-btn am-btn-default am-btn-xs am-text-secondary"><span class="am-icon-pencil-square-o"></span> 编辑</button>
                            <button class="am-btn am-btn-default am-btn-xs am-hide-sm-only"><span class="am-icon-copy"></span> 复制</button>
                            <button class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span class="am-icon-trash-o"></span> 删除</button>
                        </div>
                    </div>
                </td>
            </tr>
        <?php }?>
        </tbody>
    </table>
</div>
<script>
    $(".edit_button").click(
        function () {
            var id = $(this).data("novel_id");
            $("#novel_id").val(id);
            $("#name").val($(this).data("name"));
            $("#description").val($(this).data("description"));
            $("#author").val($(this).data("author_id"));
            $("#novel_class").val($(this).data("novel_class"));
            $("#record_status").val($(this).data("record_status"));
            $("#novel_pic").attr("src",$(this).data("pic"));
            $("#novel_status").val($(this).data("status"));
            $("#order").val($(this).data("order"));
            $("#edit_window").show();

        }
    );
    $("#add_button").click(
        function () {
            $("#novel_id").val("");
            $('form')[0].reset();
            $("#novel_pic").attr("src","");
            $("#edit_window").show();
        }
    );
    $(".del_button").click(function () {
        var name = $(this).data("name");
        if(confirm("确定要删除吗？（"+name+"）")){
            return true;
        }else{
            return false;
        }
    });

    $(".limit_button").click(function () {
        var name = $(this).data("name");
        if(confirm("确定要冻结吗？（"+name+"）")){
            return true;
        }else{
            return false;
        }
    });

</script>
</body>
</html>
