<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
</head>
<body>
<div class="panel admin-panel margin-top" id="add">
  <div class="panel-head"><input type="button" value="添加分类" id="add_button"></div>
  <div class="body-content" style="display: none;"  id="edit_window">
    <form method="post" class="form-x" action="/article/replace" id="edit_window_form" enctype="multipart/form-data">
      <div class="form-group" >
          <div class="field">
              <label class="label" style="width: 80px;">名称：</label>
              <input type="text" class="input w50" id="class_name" name="class_name" placeholder="">
          </div>
          <div class="field">
              <label class="label" style="width: 80px;">上级菜单</label>
              <select id="parent_class" name="parent_class" class="input w50">
                  <option value="0"></option>
                  <?php foreach($this->first_class as $key=>$value){?>
                      <option value="<?=$key?>"><?=$value?></option>
                  <?php }?>
              </select>
          </div>
          <div class="field">
              <label class="label" style="width: 80px;">状态：</label>
              <select id="class_status" name="class_status">
                  <option value="<?=ArticlesTypeModel::ARTICLE_CLASS_STATUS?>">正常</option>
                  <option value="<?=ArticlesTypeModel::ARTICLE_CLASS_STATUS_DEL?>">冻结</option>
              </select>
          </div>
          <div class="field">
              <label class="label" style="width: 80px;" >简介</label>
              <textarea  rows="5" class="input w50" name="description" id="description"></textarea>
          </div>
      </div>
        <div class="form-group" >
            <div class="label" style="width: 80px;">
                <label>封面：</label>
            </div>
            <div class="field">
                <img id="pic" src="" width="30px" height="30px">
                <input type="file" class="input w50" value="" id="img" name="img"  />
                <div class="tips"></div>
            </div>
        </div>

          <input type="hidden" value="" name="class_id" id="class_id">
          <button class="button bg-main icon-check-square-o" type="submit"> 提交</button>
          <button class="button bg-main icon-check-square-o" type="button" onclick="$('#edit_window').hide()"> 取消</button>
      </div>

    </form>
  </div>
</div>
<div class="panel admin-panel">
    <div class="panel-head"><strong class="icon-reorder"> 分类列表管理</strong></div>

    <table class="table table-hover text-center">
        <thead>
        <tr>
            <th class="table-id">ID</th>
            <th class="table-title">分类名称</th>
            <th class="table-type">上级分类</th>
            <th class="table-type">状态</th>
            <th class="table-date am-hide-sm-only">修改日期</th>
            <th class="table-set">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->class_list as $value){?>
            <tr>

                <td><?=$value['id']?></td>
                <td><?=$value['name']?></td>
                <td><?=$value['parent_id']?></td>
                <td><?=$value['status']== ArticlesTypeModel::ARTICLE_CLASS_STATUS?"正常":"冻结"?></td>
                <td class="am-hide-sm-only"><?=date("Y-m-d H:i:s",$value['update_time'])?></td>
                <td>
                    <div class="am-btn-toolbar">
                        <div class="button-group" style="align-content: left">
                            <a class="button edit_button" data-pic="<?=\YC\Common::getUrl($value['pic'])?>" data-status="<?=$value['status']?>" data-content="<?=$value['content']?>" data-id="<?=$value['id']?>" data-name="<?=$value['name']?>" data-parent="<?=$value['parent_id']?>">编辑</a>
                            <a href="/novel/subject?id=<?=$value['id']?>&class_type=2" class="button"> 临时目录</a>
                            <a href="/article/list?id=<?=$value['id']?>&class_type=2" class="button"> 真实目录</a>
                        </div>
                    </div>
                </td>
            </tr>
        <?php }?>
        </tbody>
    </table>
</div>
<script>
    $(".edit_button").click(
        function () {
            var id = $(this).data("id");
            $("#class_id").val(id);
            $("#class_name").val($(this).data("name"));
            $("#parent_class").val($(this).data("parent"));
            $("#description").val($(this).data("content"));
            $("#class_status").val($(this).data("status"));
            $("#pic").attr("src",$(this).data("pic"));
            $("#edit_window").show();

        }
    );
    $("#add_button").click(
        function () {
            $("#class_id").val("");
            $('form')[0].reset();
            $("#edit_window").show();
        }
    );
</script>
</body>
</html>
