<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
</head>
<body>
<div class="panel admin-panel margin-top" id="add">
  <div class="panel-head">
      <input type="button" value="添加作者" id="add_button">
      <input type="button" value="冻结"  onclick="$('#post_type').val('status_0');$('#all_post').submit()">
      <input type="button" value="解冻"  onclick="$('#post_type').val('status_1');$('#all_post').submit()">
  </div>
  <div class="body-content" style="display: none"  id="edit_window">
    <form method="post" class="form-x" action="/article/postauthor" enctype="multipart/form-data">
      <div class="form-group" >
        <div class="label">
          <label>作者姓名：</label>
        </div>
        <div class="field">
          <input type="text" class="input w50" value="" id="name" name="name" data-validate="required:请输入作者姓名" />
          <div class="tips"></div>
        </div>
          <div class="label">
              <label>作者头像：</label>
          </div>
          <div class="field">
              <img id="author_pic" src="" width="30px" height="30px">
              <input type="file" name="img" id="img" class="input w50">
              <div class="tips"></div>
          </div>

          <div class="label">
              <label>作者类别：</label>
          </div>
          <div class="field">
            <select name="novel_class_id" id="novel_class_id" class="input w50">
                <?php foreach ($this->article_type as $value){ ?>
                    <option value="<?=$value['id']?>"><?=$value['name']?></option>
                <?php } ?>
            </select>
          </div>
          <div class="label">
              <label>作者简介：</label>
          </div>
          <div class="field">
              <input type="text" class="input w50" value="" id="description" name="description" data-validate="required:请输入作者简介" />
              <div class="tips"></div>
          </div>
          <div class="label">
              <label>作者状态：</label>
          </div>
          <div class="field">
              <select name="author_status" id="author_status">
                  <option value="<?=ArticleAuthorModel::AUTHOR_STATUS?>">正常</option>
                  <option value="<?=ArticleAuthorModel::AUTHOR_STATUS_DEL?>">冻结</option>
              </select>
          </div>
          <input type="hidden" value="" name="author_id" id="author_id">
          <button class="button bg-main icon-check-square-o" type="submit"> 提交</button>
      </div>
    </form>
  </div>
</div>
<div class="panel admin-panel">
    <div class="panel-head"><strong class="icon-reorder"> 作者管理</strong></div>
    <form action="/article/postArticleAuthor" method="post" id="all_post">
        <input type="hidden" name="post_type" id="post_type" value="status_1">
    <table class="table table-hover text-center">
        <tr>
            <th><input type="checkbox" id="selectAll"></th>
            <th>ID</th>
            <th>作者名称</th>
            <th>作者类别</th>
            <th>作者状态</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        <?php foreach($list as $value){ ?>
            <tr>
                <td><input type="checkbox" name="author_ids[]" value="<?=$value['id']?>"></td>
                <td><?=$value['id']?></td>
                <td><?=$value['author_name']?></td>
                <td><?=isset($this->article_type[$value['class_type_id']])?$this->article_type[$value['class_type_id']]['name']:"未定义"?></td>
                <td><?=$value['status'] == ArticleAuthorModel::AUTHOR_STATUS?"正常":"冻结"?></td>
                <td><?=date("Y-m-d H:i:s",$value['create_time'])?></td>
                <td>
                    <div class="button-group">
                        <a class="button edit_button" data-status="<?=$value['status']?>" data-class_type_id="<?=$value['class_type_id']?>" data-pic="<?=\YC\Common::getUrl($value['pic'])?>" data-author_id="<?=$value['id']?>" data-author_name="<?=$value['author_name']?>" data-description="<?=$value['description']?>">编辑</a>
                        <a class="button" href="/novel/subject?author_id=<?=$value['id']?>&class_type=2">临时目录</a>
                     </div>
                </td>
            </tr>
        <?php }?>
        <tr>
            <td colspan="8">
                <?=$this->pageHtml?>
            </td>
        </tr>
    </table>
    </form>
</div>
<script>
    $("#selectAll").click(function () {
        if(this.checked) {
            $("input[name='author_ids[]']").attr('checked',true);
        }else {
            $("input[name='author_ids[]']").attr('checked',false);
        }
    });
    $(".edit_button").click(
        function () {
            var author_id = $(this).data("author_id");
            $("#author_id").val(author_id);
            $("#name").val($(this).data("author_name"));
            $("#description").val($(this).data("description"));
            $("#author_pic").attr("src",$(this).data("pic"));
            $("#novel_class_id").val($(this).data("class_type_id"));
            $("#author_status").val($(this).data("status"));
            $("#edit_window").show();
        }
    );
    $("#add_button").click(
        function () {
            $("#author_id").val("");
            $("#edit_window").show();
        }
    );
    $(".del_button").click(function () {
        var author_name = $(this).data("author_name");
        if(confirm("确定要删除吗？（"+author_name+"）")){
            return true;
        }else{
            return false;
        }
    });
</script>
</body>
</html>
