<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
</head>
<body>

<div class="panel admin-panel">
    <div class="panel-head"><input type="button" value="添加章节" id="add_button"></div>
    <div class="body-content" style="display:none "  id="edit_window">
        <form method="post" class="form-x" action="/article/editarticle" id="edit_window_form" enctype="multipart/form-data">
            <div class="form-group" >
                <div class="label">
                    <label>名称</label>
                </div>
                <div class="field">
                    <input type="text" class="input w50" value="" id="title" name="title" data-validate="required:请输入章节名称" />
                    <div class="tips"></div>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>顺序：</label>
                </div>
                <div class="field">
                    <input type="text" class="input w50" value="" id="order" name="order" data-validate="required:请输入章节顺序" />
                    <div class="tips"></div>
                </div>
            </div>

            <div class="form-group" >
                <div class="label">
                    <label>状态：</label>
                </div>
                <div class="field">
                    <select name="status" id="status">
                        <option value="1">正常</option>
                        <option value="-1">冻结</option>
                    </select>
                </div>
            </div>

            <div class="form-group" >
                <div class="label">
                    <label>分部：</label>
                </div>
                <div class="field">
                    <select name="is_part" id="is_part">
                        <option value="0">否</option>
                        <option value="1">是</option>
                    </select>
                </div>
            </div>

            <div class="form-group" >
                <div class="label">
                    <label>内容：</label>
                </div>
                <div class="field">
                    <textarea name="content" style="width: 500px;height: 200px" ></textarea>
                </div>
            </div>
            <input type="hidden" name="class_type" id="class_type" value="<?=$_GET['id']?>">
            <input type="hidden" name="id" value="" id="id">
            <button class="button bg-main icon-check-square-o" type="submit"> 提交</button>
        </form>
    </div>
    <div class="panel-head"><strong class="icon-reorder"> 小说目录管理</strong></div>
    <table class="table table-hover text-center">
        <tr>
            <th>ID</th>
            <th>名称</th>
            <th>状态</th>
            <th>顺序</th>
            <th>分部章节</th>
            <th>操作</th>
        </tr>
        <?php foreach($this->list as $key=>$value){
            ?>
            <tr>
                <td><?=$key+1?></td>
                <td><a target="_blank" href="<?=$this->web_url?>/tangshi/detail_<?=$value['id']?>.html"><?=$value['name']?></a></td>
                <td><?=$value['status']==1?"正常":"冻结"?></td>
                <td><?=$value['article_order']?></td>
                <td><?=$value['is_part']==1?"是":"否"?></td>
                <td>
                    <div class="button-group">
                        <a class="button edit_button" data-is_part="<?=$value['is_part']?>" data-class_type="<?=$value['class_type']?>" data-status="<?=$value['status']?>"  data-id="<?=$value['id']?>"  data-name="<?=$value['name']?>"  data-order="<?=$value['article_order']?>">编辑</a>
                    </div>
                </td>
            </tr>
        <?php }?>
        <tr>

            <td colspan="8">
                <?=$pageHtml?>
            </td>
        </tr>
    </table>
</div>
<script>
    $(".edit_button").click(
        function () {
            $("#id").val("");
            $('form')[0].reset();
            var id = $(this).data("id");
            $("#id").val(id);
            $("#title").val($(this).data("name"));
            $("#status").val($(this).data("status"));
            $("#order").val($(this).data("order"));
            $("#class_type").val($(this).data("class_type"));
            $("#is_part").val($(this).data("is_part"));
            $("#edit_window").show();

        }
    );
    $("#add_button").click(
        function () {
            $("#id").val("");
            $('form')[0].reset();
            $("#edit_window").show();
        }
    );

</script>
</body>
</html>
