<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title>诗词管理</title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
</head>
<body>

<div class="panel admin-panel">
    <div class="panel-head">
        <strong class="icon-reorder"> 诗词管理</strong>
        <div style="float: right" ><a href="/article/manageedit" target="_blank" class="button" style="height: 30px;padding: 5px 10px">添加</a></div>
    </div>

    <table class="table table-hover text-center">
        <tr>
            <th>ID</th>
            <th>名称</th>
            <th>作者</th>
            <th>内容</th>
            <th>简介</th>
            <th>翻译</th>
            <th>注释</th>
            <th>赏析</th>
            <th>分类</th>
            <th>操作</th>
        </tr>
        <?php foreach($this->list as $key=>$value){
            ?>
            <tr>
                <td><?=$value['id']?></td>
                <td><a target="_blank" href="<?=$this->web_url?>/tangshi/detail_<?=$value['id']?>.html"><?=$value['name']?></a></td>
                <td><?=$value['author']?></td>
                <td><?=substr(strip_tags($value['content']),0,30)?>...</td>
                <td><?=substr(strip_tags($value['description']),0,30)?>...</td>
                <td><?=substr(strip_tags($value['translate']),0,30)?>...</td>
                <td><?=substr(strip_tags($value['notes']),0,30)?>...</td>
                <td><?=substr(strip_tags($value['shangxi']),0,30)?>...</td>
                <td><?=ArticlesTypeModel::$articleTypeTxt[$value['class_type']]?></td>
                <td>
                    <div class="button-group">
                        <a href="/article/manageedit?id=<?=$value['id']?>" target="_blank" class="button">编辑</a>
                        <a class="button edit_finish_button">完成</a>
                    </div>
                </td>
            </tr>
        <?php }?>
        <tr>

            <td colspan="8">
                <?=$this->pageHtml?>
            </td>
        </tr>
    </table>
</div>
<script>
    $(".edit_button").click(
        function () {
            $("#id").val("");
            $('form')[0].reset();
            var id = $(this).data("id");
            $("#id").val(id);
            $("#title").val($(this).data("name"));
            $("#status").val($(this).data("status"));
            $("#order").val($(this).data("order"));
            $("#class_type").val($(this).data("class_type"));
            $("#is_part").val($(this).data("is_part"));
            $("#edit_window").show();

        }
    );
    $("#add_button").click(
        function () {
            $("#id").val("");
            $('form')[0].reset();
            $("#edit_window").show();
        }
    );

</script>
</body>
</html>
