<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title>诗词管理编辑</title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
    <script src="/js/jquery.js"></script>
    <script src="/js/pintuer.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js?3"></script>
    <script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js?2"> </script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/js/ueditorlang/zh-cn/zh-cn.js"></script>

</head>
<body>
<div class="panel-head"><strong class="icon-reorder"> 诗词管理</strong></div>
<div class="panel admin-panel">
    <div class=""></div>
    <div class="body-content">
        <form method="post" class="form-x" action="/article/managedo" id="edit_form" enctype="multipart/form-data">
            <div class="form-group" >
                <div class="label">
                    <label>类型：</label>
                </div>
                <div class="field">
                    <select name="class_type" id="class_type">
                        <option value=""></option>
                        <?php foreach (ArticlesTypeModel::$articleTypeTxt as $key=>$value){?>
                        <option value="<?=$key?>" <?=isset($this->info['class_type'])&&$this->info['class_type']==$key?"selected":""?>><?=$value?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>名称</label>
                </div>
                <div class="field">
                    <input type="text" class="input w50" value="<?=isset($this->info['name'])?$this->info['name']:""?>" id="title" name="title" data-validate="required:请输入诗词曲名称" />
                    <div class="tips"></div>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>作者：</label>
                </div>
                <div class="field">
                    <select name="author_id" id="author_id">
                        <option value=""></option>
                        <?php foreach($this->authorList as $value){ ?>
                        <option value="<?=$value['id']?>" <?=isset($this->info['author_id'])&&$this->info['author_id']==$value['id']?"selected":""?>><?=$value['author_name']?></option>
                       <?php }?>
                    </select>
                    <input type="text" id="author_name" name="author_name" value="<?=isset($this->info['author'])?$this->info['author']:""?>">
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>内容：</label>
                </div>
                <div class="field">
                    <script id="editor_content" type="text/plain" style="width:1024px;height:200px;"></script>
                    <textarea id="content" name="content" style="display: none;" ><?=$this->info['content']?:""?></textarea>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>简介：</label>
                </div>
                <div class="field">
                    <script id="editor_description" type="text/plain" style="width:1024px;height:200px;"></script>
                    <textarea id="description" name="description" style="display: none" ><?=$this->info['description']?:""?></textarea>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>翻译：</label>
                </div>
                <div class="field">
                    <script id="editor_translate" type="text/plain" style="width:1024px;height:200px;"></script>
                    <textarea id="translate" name="translate" style="display: none" ><?=$this->info['translate']?:""?></textarea>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>注释：</label>
                </div>
                <div class="field">
                    <script id="editor_notes" type="text/plain" style="width:1024px;height:200px;"></script>
                    <textarea id="notes" name="notes" style="display: none" ><?=$this->info['notes']?:""?></textarea>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>赏析：</label>
                </div>
                <div class="field">
                    <script id="editor_shangxi" type="text/plain" style="width:1024px;height:200px;"></script>
                    <textarea id="shangxi" name="shangxi" style="display: none" ><?=$this->info['shangxi']?:""?></textarea>
                </div>
            </div>

            <div class="form-group" >
                <div class="label">
                    <label>状态：</label>
                </div>
                <div class="field">
                    <select name="status" id="status">
                        <option value="1">正常</option>
                        <option value="-1">冻结</option>
                    </select>
                </div>
            </div>
            <input type="hidden" name="id" value="<?=isset($_GET['id'])?$_GET['id']:''?>" id="id">
            <button id="submit_button" class="button bg-main icon-check-square-o" type="button"> 提交</button>
        </form>
    </div>

</div>
<script>

    var ueContent = UE.getEditor('editor_content');
    var ueDes = UE.getEditor('editor_description');
    var ueTranslate = UE.getEditor('editor_translate');
    var ueNotes = UE.getEditor('editor_notes');
    var ueShangxi = UE.getEditor('editor_shangxi');

    ueContent.addListener("ready", function () {
        ueContent.setContent($("#content").val());
    });
    ueDes.addListener("ready", function () {
        ueDes.setContent($("#description").val());
    });
    ueTranslate.addListener("ready", function () {
        ueTranslate.setContent($("#translate").val());
    });
    ueNotes.addListener("ready", function () {
        ueNotes.setContent($("#notes").val());
    });
    ueShangxi.addListener("ready", function () {
        ueShangxi.setContent($("#shangxi").val());
    });

    $("#submit_button").click(
        function (){
            if($("#class_type").val() == ""){
                alert("类型不能为空");
                return false;
            }
            if($("#title").val() == ""){
                alert("名称不能为空");
                return false;
            }
            if($("#author_id").val() == ""){
                alert("作者不能为空");
                return false;
            }
            $("#content").val(ueContent.getContent());
            $("#description").val(ueDes.getContent());
            $("#translate").val(ueTranslate.getContent());
            $("#notes").val(ueNotes.getContent());
            $("#shangxi").val(ueShangxi.getContent());
            $("#author_name").val($("#author_id").find("option:selected").text());
            $("#edit_form").submit();

        }
    );

</script>
</body>
</html>
