<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
    <script src="/js/common.js"></script>
</head>
<body>
<div class="panel admin-panel margin-top" id="add">
  <div class="panel-head"><strong><span class="icon-pencil-square-o"></span> 首页推荐</strong></div>
  <div class="body-content">
      <div class="form-group">
          <div class="label" style="width: 80px;">
              <label>小说类型</label>
          </div>
          <div class="field">
              <div class="field">
              <select name="novel_class" id="novel_class" class="input w50" onchange="location.href='/web/recommend?type='+this.value">
                  <?php
                  $type = isset($_GET['type'])?$_GET['type']:1;
                  foreach (NovelModel::$_novel_class_type as $key=>$value){ ?>
                      <option value="<?=$key?>" <?=$type==$key?"selected":""?>><?=$value?></option>
                  <?php }?>
              </select>
              </div>
          </div>
          <div class="label"></div>
      </div><br>
      <div class="form-group">
        <div class="label">
          <label>小说ID：</label>
        </div>
        <div class="field">
          <input type="text" class="input w50" value="<?=$this->xiaoshuo_id?>" id="xiaoshuo_id" />
          <div class="tips"></div>
            <button class="button bg-main icon-check-square-o" data-type="wuxia" id="xiaoshuo_button" type="button"> 预览</button>
            <button class="button bg-main icon-check-square-o" data-type="wuxia" id="xiaoshuo_submit_button" type="button"> 提交</button>
        </div>
      </div>
      <div id="xiaoshuo_list">
            <?php foreach ($this->xiaoshuo_list as $value){?>
            <div>
                <span><?=$value['id']?>.</span>
                <span><img src="<?=$value['pic']?>" width="30" height="30"></span>
                <span><?=$value['author_name']?> _ </span>
                <span><?=$value['name']?></span>
            </div>
            <?php }?>
      </div>
  </div>
</div>
<script>
    $("#xiaoshuo_button").click(function () {
        var novel_type = $("#novel_class").val();
        $.ajax({
            url: "/web/novelrecomend?id=" +$("#xiaoshuo_id").val()+"&type="+novel_type,
            type: "get",
            success: function(data) {
                if(data.code == 200){
                    var html = "";
                    var ret = data.result;
                    var img = "";
                    for (var key in ret){
                        html += "<div>"
                            + "<span>"+ret[key].id+".</span>"
                            + "<span><img src='"+ret[key].pic+"' width='30' height='30'></span>"
                            + "<span>"+ret[key].author_name+" _ </span>"
                            + "<span><a href='<?=$this->web_url?>/xiaoshuo/chapter_"+ret[key].id+"_1.html' target='_blank'> "+ret[key].name+"</a><span>"
                            + "</div>";
                    }
                    $("#xiaoshuo_list").html(html);

                }else{
                    alert(data.msg);
                }

            }
        });
    });

    $("#xiaoshuo_submit_button").click(function () {
        var novel_type = $("#novel_class").val();
        $.ajax({
            url: "/web/novelrecomendpost?id=" +$("#xiaoshuo_id").val()+"&type="+novel_type,
            type: "get",
            success: function(data) {
                if(data.code == 200){
                    alert("success");
                }else{
                    alert(data.msg);
                }

            }
        });
    });

</script>
</body></html>
