<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
    <script src="/js/common.js"></script>
</head>
<body>
<div class="panel admin-panel margin-top" id="add">
  <div class="panel-head"><strong><span class="icon-pencil-square-o"></span> 首页推荐</strong></div>
  <div class="body-content">
      <div class="form-group">
        <div class="label">
          <label>武侠小说ID：</label>
        </div>
        <div class="field">
          <input type="text" class="input w50" value="" id="wuxia_id" />
          <div class="tips"></div>
            <button class="button bg-main icon-check-square-o" data-type="wuxia" id="wuxia_button" type="button"> 预览</button>
            <button class="button bg-main icon-check-square-o" data-type="wuxia" id="wuxia_submit_button" type="button"> 提交</button>
        </div>
      </div>
      <div id="wuxia">
            <?php foreach ($this->wuxia as $value){?>
            <div>
                <span><?=$value['id']?>.</span>
                <span><img src="<?=$value['pic']?>" width="30" height="30"></span>
                <span><?=$value['name']?></span>
            </div>
            <?php }?>
      </div>

      <div class="form-group">
          <div class="label">
              <label>言情小说ID：</label>
          </div>
          <div class="field">
              <input type="text" class="input w50" value="" id="yanqing_id" />
              <div class="tips"></div>
              <button class="button bg-main icon-check-square-o" data-type="yanqing" id="yanqing_button" type="button"> 预览</button>
              <button class="button bg-main icon-check-square-o" data-type="yanqing" id="yanqing_submit_button" type="button"> 提交</button>
          </div>
      </div>
      <div id="yanqing">
          <?php foreach ($this->yanqing as $value){?>
              <div>
                  <span><?=$value['id']?>.</span>
                  <span><img src="<?=$value['pic']?>" width="30" height="30"></span>
                  <span><?=$value['name']?></span>
              </div>
          <?php }?>
      </div>
  </div>
</div>
<script>
    $("#wuxia_button,#yanqing_button").click(function () {
        var novel_type = $(this).data("type");
        $.ajax({
            url: "/web/novelrecomend?id=" +$("#"+novel_type+"_id").val()+"&type="+novel_type,
            type: "get",
            success: function(data) {
                if(data.code == 200){
                    var html = "";
                    var ret = data.result;
                    var img = "";
                    for (var key in ret){
                        html += "<div>"
                            + "<span>"+ret[key].id+".</span>"
                            + "<span><img src='"+ret[key].pic+"' width='30' height='30'></span>"
                            + "<span><a href='<?=$this->web_url?>/xiaoshuo/chapter_"+ret[key].id+"_1.html' target='_blank'> "+ret[key].name+"</a><span>"
                            + "</div>";
                    }
                    $("#"+novel_type).html(html);

                }else{
                    alert(data.msg);
                }

            }
        });
    });

    $("#wuxia_submit_button,#yanqing_submit_button").click(function () {
        var novel_type = $(this).data("type");
        $.ajax({
            url: "/web/novelrecomendpost?id=" +$("#"+novel_type+"_id").val()+"&type="+novel_type,
            type: "get",
            success: function(data) {
                if(data.code == 200){
                    alert("success");
                }else{
                    alert(data.msg);
                }

            }
        });
    });

</script>
</body></html>
