<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
    <script src="/js/common.js"></script>
</head>
<body>
<div class="panel admin-panel margin-top" id="add">
  <div class="panel-head"><strong><span class="icon-pencil-square-o"></span> 首页推荐</strong></div>
  <div class="body-content">
      <div class="form-group">
        <div class="label">
          <label>武侠小说ID：</label>
        </div>
        <div class="field">
          <input type="text" class="input w50" value="" name="xuxia_id" data-validate="required:请输入标题" />
          <div class="tips"></div>
            <button class="button bg-main icon-check-square-o" id="wuxia_button" type="button"> 提交</button>
        </div>
      </div>
      <div id="wuxia">

      </div>
  </div>
</div>
<script>
    $("#wuxia_button").click(function () {
        $.ajax({
            url: "/novel/getnovelbyIds?id=" +$("#wuxia_id"),
            type: "get",
            success: function(data, code) {

            }
        });

    });


</script>
</body></html>
