<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="/css/pintuer.css">
<link rel="stylesheet" href="/css/admin.css">
<script src="/js/jquery.js"></script>
<script src="/js/pintuer.js"></script>
</head>
<body>

<div class="panel admin-panel">
    <div class="body-content" style="display:none "  id="edit_window">
        <form method="post" class="form-x" action="/novel/editTemp" id="edit_window_form" enctype="multipart/form-data">
            <div class="form-group" >
                <div class="label">
                    <label>章节title：</label>
                </div>
                <div class="field">
                    <input type="text" class="input w50" value="" id="title" name="title" data-validate="required:请输入章节名称" />
                    <div class="tips"></div>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>章节顺序：</label>
                </div>
                <div class="field">
                    <input type="text" class="input w50" value="" id="order" name="order" data-validate="required:请输入章节顺序" />
                    <div class="tips"></div>
                </div>
            </div>

            <div class="form-group" >
                <div class="label">
                    <label>章节状态：</label>
                </div>
                <div class="field">
                    <select name="status" id="status">
                        <option value="1">正常</option>
                        <option value="-1">冻结</option>
                    </select>
                </div>
            </div>
            <div class="form-group" >
                <div class="label">
                    <label>章节内容：</label>
                </div>
                <div class="field">
                    <textarea name="content" style="width: 500px;height: 200px" ></textarea>
                </div>
            </div>
            <input type="hidden" name="novel_id" id="novel_id" value="">
            <input type="hidden" name="id" value="" id="id">
            <button class="button bg-main icon-check-square-o" type="submit"> 提交</button>
        </form>
    </div>
    <div class="panel-head"><strong class="icon-reorder"> 小说临时目录管理</strong></div>
    <div class="button-group">
        <a href="/novel/subjectStatus?id=<?=$_GET['id']?>" class="button"> 就绪</a>
    </div>
    <table class="table table-hover text-center">
        <tr>
            <th>ID</th>
            <th>目录名称</th>
            <th>状态</th>
            <th>顺序</th>
            <th>操作</th>
        </tr>
        <?php foreach($list as $key=>$value){
            ?>
            <tr>
                <td><?=$key+1?></td>
                <td><?=$value['title']?></td>
                <td><?=$value['status']==1?"正常":"冻结"?></td>
                <td><?=$value['chapter_order']?></td>
                <td>
                    <div class="button-group">
                        <a class="button edit_button" data-novel_id="<?=$value['novel_id']?>" data-status="<?=$value['status']?>"  data-id="<?=$value['id']?>"  data-title="<?=$value['title']?>"  data-order="<?=$value['chapter_order']?>">编辑</a>
                    </div>
                </td>
            </tr>
        <?php }?>
        <tr>

            <td colspan="8">
                <?=$pageHtml?>
            </td>
        </tr>
    </table>
</div>
<script>
    $(".edit_button").click(
        function () {
            $("#id").val("");
            $('form')[0].reset();
            var id = $(this).data("id");
            $("#id").val(id);
            $("#title").val($(this).data("title"));
            $("#status").val($(this).data("status"));
            $("#order").val($(this).data("order"));
            $("#novel_id").val($(this).data("novel_id"));
            $("#edit_window").show();

        }
    );
    $("#add_button").click(
        function () {
            $("#id").val("");
            $('form')[0].reset();
            $("#edit_window").show();
        }
    );

</script>
</body>
</html>
